import type { GeoPrecision } from "./types";

/**
 * Gazetteer: countries and major cities (generated by scripts/build-geo.mjs).
 * Pure functions over the data so the same code runs on the server (headline
 * geocoding) and in the browser (search, fly-to) where the JSON is lazy-loaded.
 */

export interface CountryRow {
  iso2: string;
  iso3: string;
  name: string;
  aliases: string[];
  /** "Ukrainian" — names an actor more often than a location. */
  demonyms: string[];
  region: string;
  subregion: string;
  capital: string | null;
  lat: number;
  lon: number;
  bbox: [number, number, number, number] | null;
  area: number;
}

export interface CityRow {
  name: string;
  iso2: string;
  lat: number;
  lon: number;
  pop: number;
  cap?: 1;
}

export interface GazetteerData {
  countries: CountryRow[];
  cities: CityRow[];
}

export interface GeoMatch {
  lat: number;
  lon: number;
  precision: GeoPrecision;
  place: string;
  country: string;
  /** The text that matched. */
  matched: string;
  /** Only a demonym matched ("Israeli army…"): the actor's country, not necessarily the place. */
  weak?: boolean;
}

/** City names that collide with everyday English words or first names. */
const CITY_STOP = new Set([
  "mobile", "reading", "nice", "split", "bath", "victoria", "hope", "aurora",
  "independence", "lincoln", "jackson", "madison", "charlotte", "austin",
  "norman", "florence", "temple", "surprise", "enterprise", "garland",
  "orange", "irving", "mesa", "gary", "president", "leon", "santiago de",
  "cork", "wake", "march", "police", "mercedes", "trinidad", "concord",
  "richmond", "plano", "sale", "deal", "worth", "fort",
]);

/** Short or ambiguous country references headlines lean on. */
const EXTRA_COUNTRY_ALIASES: Record<string, string> = {
  us: "US", "u.s": "US", "u.s.": "US", usa: "US", america: "US", washington: "US",
  uk: "GB", "u.k": "GB", "u.k.": "GB", britain: "GB", british: "GB", england: "GB",
  uae: "AE", emirati: "AE", drc: "CD", "dr congo": "CD", congo: "CD", congolese: "CD",
  gaza: "PS", "west bank": "PS", palestinian: "PS", palestinians: "PS",
  kremlin: "RU", moscow: "RU", beijing: "CN", tehran: "IR", "north korea": "KP",
  "south korea": "KR", "north korean": "KP", "south korean": "KR", taiwanese: "TW",
  "czech republic": "CZ", turkey: "TR", "ivory coast": "CI", burma: "MM",
  houthi: "YE", houthis: "YE", hezbollah: "LB", hamas: "PS", taliban: "AF",
  sahel: "ML", crimea: "UA", donbas: "UA", kashmir: "IN", darfur: "SD",
};

const EXTRA_COUNTRY_PLACES: Record<string, { lat: number; lon: number; place: string }> = {
  gaza: { lat: 31.5, lon: 34.45, place: "Gaza Strip" },
  "west bank": { lat: 31.95, lon: 35.25, place: "West Bank" },
  crimea: { lat: 45.3, lon: 34.4, place: "Crimea" },
  donbas: { lat: 48.0, lon: 38.0, place: "Donbas" },
  darfur: { lat: 13.5, lon: 24.5, place: "Darfur" },
  kashmir: { lat: 34.1, lon: 74.8, place: "Kashmir" },
  sahel: { lat: 15.0, lon: 0.0, place: "Sahel" },
};

type Entry =
  | { kind: "country"; row: CountryRow; place?: { lat: number; lon: number; place: string }; weak?: boolean }
  | { kind: "city"; row: CityRow };

interface Index {
  phrases: Map<string, Entry[]>;
  byIso2: Map<string, CountryRow>;
  maxWords: number;
}

const indexCache = new WeakMap<GazetteerData, Index>();

export function stripDiacritics(s: string): string {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "");
}

function norm(s: string): string {
  return stripDiacritics(s).toLowerCase().replace(/[’']/g, "'").trim();
}

function buildIndex(data: GazetteerData): Index {
  const phrases = new Map<string, Entry[]>();
  const byIso2 = new Map<string, CountryRow>();
  let maxWords = 1;
  const add = (phrase: string, e: Entry) => {
    const k = norm(phrase);
    if (!k || k.length < 3) return;
    maxWords = Math.max(maxWords, k.split(/\s+/).length);
    const list = phrases.get(k);
    if (list) list.push(e);
    else phrases.set(k, [e]);
  };

  for (const c of data.countries) {
    byIso2.set(c.iso2, c);
    add(c.name, { kind: "country", row: c });
    for (const a of c.aliases) add(a, { kind: "country", row: c });
    for (const d of c.demonyms) add(d, { kind: "country", row: c, weak: true });
  }
  for (const [alias, iso2] of Object.entries(EXTRA_COUNTRY_ALIASES)) {
    const row = byIso2.get(iso2);
    if (!row) continue;
    const k = norm(alias);
    const e: Entry = { kind: "country", row, place: EXTRA_COUNTRY_PLACES[alias] };
    maxWords = Math.max(maxWords, k.split(/\s+/).length);
    // Explicit aliases win over anything the generated data put there.
    phrases.set(k, [e]);
  }
  for (const city of data.cities) {
    const k = norm(city.name);
    if (CITY_STOP.has(k) || k.length < 4) continue;
    // Don't let a city shadow a country or explicit alias of the same name.
    const existing = phrases.get(k);
    if (existing?.some((e) => e.kind === "country")) continue;
    add(city.name, { kind: "city", row: city });
  }
  return { phrases, byIso2, maxWords };
}

function getIndex(data: GazetteerData): Index {
  let idx = indexCache.get(data);
  if (!idx) {
    idx = buildIndex(data);
    indexCache.set(data, idx);
  }
  return idx;
}

export function countryByIso2(data: GazetteerData, iso2: string | undefined | null): CountryRow | undefined {
  if (!iso2) return undefined;
  return getIndex(data).byIso2.get(iso2.toUpperCase());
}

/**
 * Find the most specific place a headline is about. Only capitalised phrases
 * count (proper nouns), longest match wins, and a city is preferred when the
 * text also names its country — "Kharkiv, Ukraine" beats a stray "Ukraine".
 */
export function geocodeText(data: GazetteerData, text: string): GeoMatch | null {
  const { phrases, maxWords } = getIndex(data);
  const words = stripDiacritics(text).match(/[A-Za-z][A-Za-z'’.-]*/g) ?? [];
  // Possessives in either apostrophe ("Kyiv's", "Kyiv’s"), then trailing punctuation.
  const clean = words.map((w) => w.replace(/['’]s$/i, "").replace(/[.'’-]+$/, ""));

  const cities: Array<{ row: CityRow; pos: number; text: string }> = [];
  const countries: Array<{
    row: CountryRow;
    pos: number;
    text: string;
    sub?: { lat: number; lon: number; place: string };
    weak?: boolean;
  }> = [];

  let i = 0;
  while (i < clean.length) {
    let matched = 0;
    for (let n = Math.min(maxWords, clean.length - i); n >= 1; n--) {
      const slice = clean.slice(i, i + n);
      // Proper-noun gate: the phrase must start with a capital letter, and an
      // all-caps short token (US, UK) is accepted as an acronym.
      if (!/^[A-Z]/.test(slice[0])) continue;
      const phrase = norm(slice.join(" "));
      const hits = phrases.get(phrase) ?? phrases.get(phrase.replace(/\./g, ""));
      if (!hits) continue;
      const surface = slice.join(" ");
      for (const h of hits) {
        if (h.kind === "city") cities.push({ row: h.row, pos: i, text: surface });
        else countries.push({ row: h.row, pos: i, text: surface, sub: h.place, weak: h.weak });
      }
      matched = n;
      break;
    }
    i += matched || 1;
  }

  if (cities.length) {
    const mentioned = new Set(countries.map((c) => c.row.iso2));
    const scored = cities
      .map((c) => ({
        ...c,
        score: (mentioned.has(c.row.iso2) ? 1e9 : 0) + (c.row.cap ? 5e6 : 0) + c.row.pop - c.pos * 1e5,
      }))
      .sort((a, b) => b.score - a.score);
    const best = scored[0];
    // A lone, small, non-capital city with no supporting country mention is
    // too ambiguous (e.g. surnames) — fall through to country-level.
    if (mentioned.has(best.row.iso2) || best.row.cap || best.row.pop >= 1_000_000 || !countries.length) {
      const country = getIndex(data).byIso2.get(best.row.iso2);
      return {
        lat: best.row.lat,
        lon: best.row.lon,
        precision: "city",
        place: country ? `${best.row.name}, ${country.name}` : best.row.name,
        country: best.row.iso2,
        matched: best.text,
      };
    }
  }

  if (countries.length) {
    // A named sub-region ("Gaza", "Donbas") beats a country name, which beats
    // a demonym — "Israeli strikes on Gaza" happened in Gaza, not Israel.
    const rank = (c: (typeof countries)[number]) => (c.sub ? 0 : c.weak ? 2 : 1);
    const first = countries.sort((a, b) => rank(a) - rank(b) || a.pos - b.pos)[0];
    const sub = first.sub;
    if (sub) {
      return {
        lat: sub.lat,
        lon: sub.lon,
        precision: "region",
        place: sub.place,
        country: first.row.iso2,
        matched: first.text,
      };
    }
    return {
      lat: first.row.lat,
      lon: first.row.lon,
      precision: "country",
      place: first.row.name,
      country: first.row.iso2,
      matched: first.text,
      ...(first.weak ? { weak: true } : {}),
    };
  }
  return null;
}

const iso3Index = new WeakMap<GazetteerData, Map<string, CountryRow>>();

/** ISO 3166-1 alpha-3 lookup (CAMEO actor country codes are alpha-3). */
export function countryByIso3(data: GazetteerData, iso3: string | undefined | null): CountryRow | undefined {
  if (!iso3) return undefined;
  let idx = iso3Index.get(data);
  if (!idx) {
    idx = new Map(data.countries.map((c) => [c.iso3, c]));
    iso3Index.set(data, idx);
  }
  return idx.get(iso3.toUpperCase());
}

const nameIndex = new WeakMap<GazetteerData, Map<string, CountryRow>>();

/** Exact (case- and accent-insensitive) country lookup by name or alias. */
export function countryByName(data: GazetteerData, name: string | undefined | null): CountryRow | undefined {
  if (!name) return undefined;
  let idx = nameIndex.get(data);
  if (!idx) {
    idx = new Map();
    for (const c of data.countries) {
      for (const n of [c.name, c.iso3, ...c.aliases]) idx.set(norm(n), c);
    }
    for (const [alias, iso2] of Object.entries(EXTRA_COUNTRY_ALIASES)) {
      const row = data.countries.find((c) => c.iso2 === iso2);
      if (row && !idx.has(alias)) idx.set(alias, row);
    }
    nameIndex.set(data, idx);
  }
  return idx.get(norm(name));
}
